logging:
  level:
    liquibase: info
    root: info
    sql: info
    web: info
    
server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: true
    enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4545/postgres?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa: ##JPA Properties
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    
